Repository valocode/bubbly, pull requests merged in 2021-04, with the labels that each got.

#57 writing a bubbly file and tutorial for gosec
  docs/docs.go
  integration/apply_test.go
  integration/testdata/gosec/gosec.bubbly
  integration/testdata/gosec/results.json
  integration/testdata/schema/schema.bubbly
  website/docs/tutorials/gosec-metrics.md
  website/sidebars.js
Labels: bubbly, documentation

#59 Move website directory to docs directory
  .github/workflows/docs-build-deploy.yaml
  README.md
  docs/.gitignore
  docs/BESTPRACTICES.md
  docs/CLI_DESIGN.md
  docs/CLI_SYNTAX.md
  docs/CONTRIBUTING.md
  docs/DESIGN.md
  docs/IMPLEMENTATION.md
  docs/README.md
  docs/SPECIFICATION.md
  docs/TESTING.md
  docs/babel.config.js
  docs/docs/api/api.md
  docs/docs/cli/bubbly-agent.md
  docs/docs/cli/bubbly-apply.md
  docs/docs/cli/bubbly-get.md
  docs/docs/cli/bubbly-schema.md
  docs/docs/cli/bubbly.md
  docs/docs/cli/schema/bubbly-schema-apply.md
  docs/docs/contributing/contributing.md
  docs/docs/current-status/status.md
  docs/docs/future/future.md
  docs/docs/getting-started/getting-started.md
  docs/docs/introduction/contributing.md
  docs/docs/introduction/core-concepts.md
  docs/docs/introduction/introduction.md
  docs/docs/introduction/use-cases.md
  docs/docs/resources/kinds.md
  docs/docs/resources/overview.md
  docs/docs/schema/schema.md
  docs/docs/tutorials/github-metrics.md
  docs/docs/tutorials/gosec-metrics.md
  docs/docs/tutorials/snyk-metrics.md
  docs/docs/tutorials/tutorial1.bubbly
  docs/docs/tutorials/tutorial1.schema
  docs/docusaurus.config.js
  docs/files/Radix-Txn-MemDB.pdf
  docs/images/architecture-multi.drawio.svg
  docs/images/architecture-multi.png
  docs/images/architecture-single.drawio.svg
  docs/images/architecture-single.png
  docs/images/example-data-model-testing.drawio.svg
  docs/images/grafana-dashboard-bubbles.drawio.svg
  docs/images/grafana-dashboard-list-panels.png
  docs/images/grafana-table-panel.png
  docs/images/hcl-schema-translation-workflow.drawio.svg
  docs/images/high-level-arch.drawio.svg
  docs/images/high-level-pipeline.drawio.svg
  docs/images/high-level-sequence-diagram.drawio.svg
  docs/package.json
  docs/sidebars.js
  docs/src/css/custom.css
  docs/src/pages/styles.module.css
  docs/static/.nojekyll
  docs/static/img/bubbly-blue-wide.png
  docs/static/img/logo.svg
  docs/yarn.lock
Labels: cleanup, documentation

#60 Fix formatting for lists in README
  README.md
Labels: cleanup

#64 Set ClientType for agent cmd only if agent command is actually run
  cmd/agent/agent.go
Labels: bug

#71 Feat/store mem connect
  agent/component/datastore/data_store.go
  agent/component/datastore/handler.go
  go.mod
  go.sum
  store/cockroachdb.go
  store/graphql.go
  store/mem.go
  store/mem_test.go
  store/postgres.go
  store/provider.go
  store/schemagraph.go
  store/store.go
  store/store_test.go
  store/triggers_test.go
Labels: enhancement

#76 Fix the integration test for SPDX data by rewriting the URLs.
  integration/testdata/resources/v1/extract/spdx-licenses.bubbly
Labels: bug

#75 Purge CI workflow which was building Docker images on each PR to this repo
  .github/workflows/ci.yaml
Labels: cleanup

#80 Add order_by argument support to GraphQL and the tests for it.
  store/graphql.go
  store/postgres_graphql.go
  store/schema.go
  store/schemagraph.go
  store/store.go
  store/store_test.go
  store/testdata/sqlgen/data6.hcl
  store/testdata/sqlgen/tables6.hcl
Labels: enhancement

#81 Add distinct_on argument support to GraphQL and the tests for it.
  store/graphql.go
  store/postgres_graphql.go
  store/store_test.go
  store/testdata/sqlgen/data7.hcl
  store/testdata/sqlgen/tables7.hcl
Labels: enhancement

#85 .github/workflows/integration.yaml: Take gosec into use
  .github/workflows/integration.yaml
Labels: enhancement

#93 Make dockertest utility use the BubblyContext to avoid hard coded values
  store/postgres_migration_test.go
  test/dockertest.go
Labels: enhancement

#92 Alternative implementation for `order_by` and `distinct_on` arguments.
  store/postgres_graphql.go
Labels: cleanup

#94 Add (a very limited) limit argument support to GraphQL
  store/postgres_graphql.go
  store/store_test.go
  store/testdata/sqlgen/data8.hcl
  store/testdata/sqlgen/tables8.hcl
Labels: enhancement

#95 Fix #70 (GraphQL schema graph neighbours issue)
  store/datatree_test.go
  store/graphql.go
  store/schemagraph.go
  store/schemagraph_test.go
Labels: bug
