Repository valocode/bubbly, pull requests merged in 2021-05, with the labels that each got.

#101 Avoid linking to external copy of license in README.
  README.md
Labels: cleanup

#102 Update README header
  README.md
Labels: enhancement

#108 Add Docker image build and push to `goreleaser`
  .dockerignore
  .gitignore
  .goreleaser.yml
  Dockerfile.goreleaser
Labels: enhancement

#109 fix: add a hook to `goreleaser` to install `swag` before starting a build
  .goreleaser.yml
Labels: bug

#114 fix: link to swagger docs
  docs/docs/api/api.md
Labels: bug, documentation

#118 Fix duplicate StoreConfig in AgentConfig. Cleanup CLI color use
  cmd/agent/agent.go
  cmd/release/create/create.go
  cmd/release/eval/eval.go
  config/config.go
  config/defaults.go
  main.go
Labels: bug, cleanup
