Repository valocode/bubbly, pull requests merged in 2021-03, with the labels that each got.

#14 cleaning up Readme file
  README.md
  website/sidebars.js
Labels: cleanup, documentation

#33 Update Dockerfile with best practices
  Dockerfile
Labels: docker

#36 Introduce `run` resource trigger endpoint with zip/json support
  agent/component/worker/handler.go
  agent/component/worker/worker.go
  go.mod
  integration/apply_test.go
  integration/testdata/resources/v1/run/remote_run_with_remote_input.bubbly
  integration/testdata/sonarqube/sonarqube-example.zip
  interval/json.go
  interval/worker.go
  interval/worker_test.go
  interval/zip.go
  server/resource.go
  server/routes.go
  server/run.go
  store/triggers.go
  website/docs/introduction/core-concepts.md
  website/docs/resources/kinds.md
Labels: enhancement

#40 Remove redundant breaks from migrations.go
  store/migration.go
Labels: cleanup

#43 Fix Echo's `Bind` behaviour to use the more precise `BindBody`
  go.mod
  go.sum
  server/graphql.go
  server/resource.go
  server/schema.go
  server/upload.go
Labels: bug

#41 Adding a bubbly file for Snyk information
  README.md
  api/v1/criteria.go
  api/v1/operation.go
  integration/apply_test.go
  integration/testdata/schema/schema.bubbly
  integration/testdata/snyk/snyk-pipeline.bubbly
  integration/testdata/snyk/test.json
  website/docs/tutorials/snyk-metrics.md
  website/sidebars.js
Labels: data, documentation

#48 Remove unused tables from the test schema. Clean-up comments.
  integration/testdata/schema/schema.bubbly
  store/testdata/tables.hcl
Labels: cleanup

#44 Upgrading Docusaurus dependencies
  website/yarn.lock
Labels: cleanup, security

#55 Update GitHub Actions to Go 1.16
  .github/workflows/integration.yaml
  .github/workflows/simple.yaml
Labels: enhancement

#56 Docs deploy should run on main (typo)
  .github/workflows/docs-build-deploy.yaml
Labels: cleanup
